### PR TITLE
Add TaskValidDependency

### PR DESCRIPTION
**Pull request by christinaholt**
The TaskValidDependency is used to check whether a task is valid for

given cycle. This comes in handy when setting up complex
ndencies
for workflows in which the completion of a cycle depends on a task

may or may not have needed to run in that cycle.

An example:
You declare two cycledefs, prep and fcst, in which fcst runs a
deterministic forecast once daily, and requires a background ensemble to
run 6 hours prior to the forecast. The prep cycles run a
task named 'bkg_ens_stats', while the the fcst cycles run a task
'forecast'. Successful completion of a cycle depends (among other
things) on both of these tasks having completed, but not for every
cycle. A dependency then, for any valid cycle to be complete could
be:

<and>
  <or>
   <not><taskvalid task="bkg_ens_stats"/></not>
   <taskdep task="bkg_ens_stats"/>
  </or>
  <or>
   <not><taskvalid task="forecast"/></not>
   <taskdep task="forecast"/>
  </or>
</and>

This dependency would check whether a task should run and if it should,
that it completed successfully.

### CODE REVIEW

**Comment by christopherwharrop** [comment]
On first look, I only see one thing that might be an issue.  In dependency.rb 

````
 808    #####################################################                                                                                                                                                                                                                    
 809    #                                                                                                                                                                                                                                                                        
 810    # Resolved?                                                                                                                                                                                                                                                              
 811    #                                                                                                                                                                                                                                                                        
 812    #####################################################                                                                                                                                                                                                                    
 813    def resolved?(d)
 814
 815       # Get the jobs for this cycle                                                                                                                                                                                                                                         
 816       return false if d.jobList.nil?
 817       return false if d.tasks[@task].nil?
 818
 819       checkjob=d.tasks[@task]
 820       checkjob=checkjob.localize(d.cycle) unless checkjob.nil?
 821
 822       # Get the mandatory task attribute                                                                                                                                                                                                                                    
 823       cycle_is_valid=true
 824       unless checkjob.attributes[:cycledefs].nil?
 825         taskcycledefs=d.cycledefs.find_all { |cycledef| checkjob.attributes[:cycledefs].split(/[\s,]+/).member?(cycledef.group) }
 826         # Cycle is invalid for this task if the cycle is not a member of the tasks cycle list                                                                                                                                                                               
 827         unless taskcycledefs.any? { |cycledef| cycledef.member?(d.cycle) }
 828           cycle_is_valid=false
 829         end
 830       end  # unless                                                                                                                                                                                                                                                         
 831
 832      return cycle_is_valid
 833    end
````

````
 835    #####################################################                                                                                                                                                                                                                    
 836    #                                                                                                                                                                                                                                                                        
 837    # Query                                                                                                                                                                                                                                                                  
 838    #                                                                                                                                                                                                                                                                        
 839    #####################################################                                                                                                                                                                                                                    
 840    def query(d)
 841
 842
 843       # Set the job to check                                                                                                                                                                                                                                                
 844
 845       # Get the jobs for this cycle                                                                                                                                                                                                                                         
 846       return [{:dep=>"#{@task}", :msg=>"is not valid", :resolved=>false }] if d.jobList.nil?
 847       return [{:dep=>"#{@task}", :msg=>"is not valid", :resolved=>false }] if d.tasks[@task].nil?
 848
 849       checkjob=d.tasks[@task]
 850       checkjob=checkjob.localize(d.cycle) unless checkjob.nil?
 851
 852       cycle_is_valid=true
 853       unless checkjob.attributes[:cycledefs].nil?
 854         taskcycledefs=d.cycledefs.find_all { |cycledef| checkjob.attributes[:cycledefs].split(/[\s,]+/).member?(cycledef.group) }
 855         # Cycle is invalid for this task if the cycle is not a member of the tasks cycle list                                                                                                                                                                               
 856         unless taskcycledefs.any? { |cycledef| cycledef.member?(d.cycle) }
 857           cycle_is_valid=false
 858         end
 859       end  # unless                                                                                                                                                                                                                                                         
 860
 861      if cycle_is_valid
 862        return [{:dep=>"#{@task}", :msg=>"is valid", :resolved=>true }]
 863      else
 864        return [{:dep=>"#{@task}", :msg=>"is not valid", :resolved=>false }]
 865      end
 866    end
 867
 868  end
````

This dependency should not depend on the existence of active jobs or its localized contents.  It only depends on whether the d.cycle is a member of at least one task cycledef.  So, unless I'm misunderstanding, lines 816, 820, 846, and 850 should be removed.  I  think lines 816 and 846 will lead to false negatives in some edge cases.  I believe lines 820 and 850 are just unnecessary.  Can you take a look and see if my analysis is correct?

**Comment by christinaholt** [comment]
I agree, 820 and 850 are unnecessary. That condition should never be met at that point given lines 817 and 847. 

After a quick test without lines 816 and 846, seems that those are also unnecessary. 

I can push the change without these 4 lines, if that's the easiest way to proceed.

**Comment by christopherwharrop** [comment]
Thank you for verifying.  Yes, please push the change.  I should be able to merge this soon.

**Comment by christinaholt** [comment]
I pushed the change with those lines removed. Let me know if you need anything else. :)

**Review by christopherwharrop — APPROVED** [review]

**Pull request merged**
